# added for profile
spring.profiles.active: dev

# the general settings for task_system application
app:
  # the application name
  name: finance

# web container config
server.port: 8080

tax:
  rate_min: 0.141
  rate_max: 0.217
  line: 30000


